### ISSUE TITLE
Push new version to Hackage for GHC 7.10

### ISSUE THREAD

**Issue by FranklinChen** [scvalex/sexp#4]
Can you upload a new version of `sexp` to Hackage that supports GHC 7.10?

**Comment by FranklinChen** [comment]
Hi, I've been waiting a month on this, having had to install from master instead of from Hackage. It seems like the code is ready to go, but just hasn't been tagged with a new version and uploaded yet.

**Comment by scvalex** [comment]
Hi.   I'm probably not going to get around to this soon.  Feel free to fork the project and upload a new version to hackage (I know you could upload over other people's packages in the old hackage,  so I assume you also do it in the new one too).

**Comment by magthe** [comment]
Yes, please do that :)

**Comment by stla** [comment]
I cannot install sex-0.7 with cabal install. Is there a newer version ?
